// Auto-generated by beacon_auto_update.py
// Last updated: 2026-02-22T07:00:01.839347

export const SHOWCASE = [
  {
    image: '/screenshots/dashboard-tui.png',
    title: 'Cognitive Dashboard',
    description: 'Real-time TUI monitoring 24 services, drift score, bus health, cognitive weights, and factory status.',
    tags: ['TUI', 'Rich', 'Python'],
  },
  {
    image: '/screenshots/factory-swarm.png',
    title: 'Factory Swarm',
    description: 'Multi-agent swarm — 6 Claude Code agents in parallel across a BenQ ultrawide, orchestrated by DAG scheduler.',
    tags: ['Multi-Agent', 'Orchestration'],
  },
  {
    image: '/screenshots/activemirror-id.jpg',
    title: 'ActiveMirror Identity',
    description: 'User-sovereign protocol. Your AI identity is a portable file — stored in your files, not theirs.',
    tags: ['Identity', 'Sovereignty'], portrait: true,
  },
  {
    image: '/screenshots/mirrorbrain-pulse.png',
    title: 'MirrorBrain Mobile',
    description: 'Android companion. Policy enforcement, cortex routing, skill reliability, device mesh — all on-device.',
    tags: ['Android', 'Kotlin'], portrait: true,
  },
  {
    image: '/screenshots/dashboard-neurodivergent.png',
    title: 'Neurodivergent Focus Mode',
    description: 'Low-stimulation dashboard with single-task focus, ambient status, and cognitive load meter. Designed for ADHD/autism.',
    tags: ['Dashboard', 'Accessibility'],
  },
  {
    image: '/screenshots/dashboard-sysadmin.png',
    title: 'Sysadmin Terminal',
    description: 'Full-screen terminal dashboard — service grid, log tail, drift score, process map. Built for ops.',
    tags: ['Dashboard', 'Terminal'],
  },
  {
    image: '/screenshots/dashboard-enterprise.png',
    title: 'Enterprise Command',
    description: 'Multi-team dashboard with SLA tracking, governance compliance, role-based views. Enterprise-grade sovereign AI.',
    tags: ['Dashboard', 'Enterprise'],
  },
  {
    image: '/screenshots/dashboard-creative.png',
    title: 'Creative Studio',
    description: 'Visual dashboard with mood-responsive theming, project canvas, and inspiration feed. For builders and makers.',
    tags: ['Dashboard', 'Creative'],
  },
];

export const ARTICLES = [
  {
    slug: 'the-threat-model-was-incomplete',
    title: 'The Threat Model Was Incomplete',
    date: '2026-02-21',
    description: 'The threat model was incomplete. I built attestation chains for 70 models,',
    tags: ['ai-governance', 'operator-drift', 'self-awareness', 'cognitive-security', 'orchestrator-model'],
  },
  {
    slug: 'the-frontier-of-endless-possibilities',
    title: 'The Frontier of Endless Possibilities',
    date: '2026-02-20',
    description: 'The technological landscape has shifted from tools to agents and from digital to biological-sovereign. Here is the map o',
    tags: [],
  },
  {
    slug: 'sovereignty-is-an-architecture-decision-not-a-philosophy',
    title: 'Sovereignty Is an Architecture Decision, Not a Philosophy',
    date: '2026-02-20',
    description: 'Sovereignty in AI isn\'t about ideology. It\'s about control surfaces.  When',
    tags: ['sovereign ai', 'infrastructure', 'mesh networks', 'data residency', 'compute sovereignty'],
  },
  {
    slug: 'governance-that-runs',
    title: 'Governance That Runs',
    date: '2026-02-20',
    description: 'Governance becomes real when it enforces itself at runtime, not when',
    tags: ['governance', 'sovereignty', 'runtime enforcement', 'system integrity', 'adversarial testing'],
  },
  {
    slug: 'trust-is-the-substrate-not-the-feature',
    title: 'Trust Is the Substrate, Not the Feature',
    date: '2026-02-19',
    description: '# Trust Is the Substrate, Not the Feature  Security is not a layer you',
    tags: ['sovereign ai', 'security', 'naoris protocol', 'mesh networks', 'blockchain'],
  },
  {
    slug: 'the-mirror-that-detects-fakes',
    title: 'The Mirror That Detects Fakes',
    date: '2026-02-19',
    description: 'The cognitive mirror and the fake detector are the same machine.  That\'s',
    tags: ['sovereign-systems', 'deepfake-detection', 'cognitive-mirror', 'architecture', 'intent-modeling'],
  },
  {
    slug: 'the-infrastructure-nobody-can-see',
    title: 'The Infrastructure Nobody Can See',
    date: '2026-02-18',
    description: 'Ten months of infrastructure. Nobody can see it.  That\'s not a complaint.',
    tags: ['sovereignty', 'mesh-networks', 'building', 'visibility', 'architecture'],
  },
  {
    slug: 'the-tax-of-partial-attention',
    title: 'The Tax of Partial Attention',
    date: '2026-02-17',
    description: 'The cost of an unresolved task isn\'\'t the task itself — it\'\'s the attention',
    tags: ['sovereignty', 'systems thinking', 'cognitive load', 'attention architecture', 'building in public'],
  },
  {
    slug: 'kavach-is-not-a-product-it-s-a-proof',
    title: 'Kavach Is Not a Product. It\'s a Proof.',
    date: '2026-02-17',
    description: '# Kavach Is Not a Product. It\'\'s a Proof.  Ten months of infrastructure',
    tags: ['kavach', 'sovereign-ai', 'india', 'fraud-detection', 'infrastructure'],
  },
  {
    slug: 'the-infrastructure-nobody-sees',
    title: 'The Infrastructure Nobody Sees',
    date: '2026-02-16',
    description: 'I\'\'ve been building digital plumbing for ten months, and most of it',
    tags: ['sovereign-ai', 'digital-infrastructure', 'oauth', 'platform-integration', 'dev-advocacy'],
  },
  {
    slug: 'the-gap-between-building-and-shipping',
    title: 'The Gap Between Building and Shipping',
    date: '2026-02-16',
    description: 'I built 10 months of infrastructure nobody can see.  The memory bus works.',
    tags: ['sovereignty', 'infrastructure', 'self-modifying-systems', 'voice-interface', 'continuity'],
  },
  {
    slug: 'time-is-a-debugger',
    title: 'Time Is a Debugger',
    date: '2026-02-15',
    description: 'The most reliable indicator of whether a stabilization mechanism works',
    tags: ['stability', 'time-weighted systems', 'sovereign ai', 'empirical design', 'architecture decisions'],
  },
  {
    slug: 'the-paradox-of-sovereign-evolution',
    title: 'The Paradox of Sovereign Evolution',
    date: '2026-02-15',
    description: 'The safest AI systems aren\'t the ones that never change — they\'re the',
    tags: ['agent-governance', 'self-modification', 'safety', 'architecture', 'sovereignty'],
  },
  {
    slug: 'the-bus-is-not-the-feature',
    title: 'The Bus Is Not the Feature',
    date: '2026-02-15',
    description: 'I\'ve spent the last few weeks building infrastructure nobody asked for.  A',
    tags: ['sovereignty', 'architecture', 'identity', 'integration', 'systems-thinking'],
  },
  {
    slug: 'the-visibility-paradox',
    title: 'The Visibility Paradox',
    date: '2026-02-14',
    description: 'I have built a sovereign AI operating system over ten months. The world has seen exactly none of it. This is a problem I',
    tags: ['shipping', 'visibility', 'sovereign-infrastructure', 'building-in-public'],
  },
];

export const STATS = [
  { value: '107', label: 'Repos' },
  { value: '14', label: 'AI Models' },
  { value: '24', label: 'Services' },
  { value: '12k', label: 'Lines in OS' },
  { value: '23', label: 'Guard Rules' },
  { value: '0', label: 'Cloud Dependencies' },
];
