// Auto-generated by beacon_auto_update.py
// Last updated: 2026-02-18T23:12:58.996221

export const SHOWCASE = [
  {
    image: '/screenshots/dashboard-tui.png',
    title: 'Cognitive Dashboard',
    description: 'Real-time TUI monitoring 24 services, drift score, bus health, cognitive weights, and factory status.',
    tags: ['TUI', 'Rich', 'Python'],
  },
  {
    image: '/screenshots/factory-swarm.png',
    title: 'Factory Swarm',
    description: 'Multi-agent swarm — 6 Claude Code agents in parallel across a BenQ ultrawide, orchestrated by DAG scheduler.',
    tags: ['Multi-Agent', 'Orchestration'],
  },
  {
    image: '/screenshots/activemirror-id.jpg',
    title: 'ActiveMirror Identity',
    description: 'User-sovereign protocol. Your AI identity is a portable file — stored in your files, not theirs.',
    tags: ['Identity', 'Sovereignty'], portrait: true,
  },
  {
    image: '/screenshots/mirrorbrain-pulse.png',
    title: 'MirrorBrain Mobile',
    description: 'Android companion. Policy enforcement, cortex routing, skill reliability, device mesh — all on-device.',
    tags: ['Android', 'Kotlin'], portrait: true,
  },
  {
    image: '/screenshots/dashboard-neurodivergent.png',
    title: 'Neurodivergent Focus Mode',
    description: 'Low-stimulation dashboard with single-task focus, ambient status, and cognitive load meter. Designed for ADHD/autism.',
    tags: ['Dashboard', 'Accessibility'],
  },
  {
    image: '/screenshots/dashboard-sysadmin.png',
    title: 'Sysadmin Terminal',
    description: 'Full-screen terminal dashboard — service grid, log tail, drift score, process map. Built for ops.',
    tags: ['Dashboard', 'Terminal'],
  },
  {
    image: '/screenshots/dashboard-enterprise.png',
    title: 'Enterprise Command',
    description: 'Multi-team dashboard with SLA tracking, governance compliance, role-based views. Enterprise-grade sovereign AI.',
    tags: ['Dashboard', 'Enterprise'],
  },
  {
    image: '/screenshots/dashboard-creative.png',
    title: 'Creative Studio',
    description: 'Visual dashboard with mood-responsive theming, project canvas, and inspiration feed. For builders and makers.',
    tags: ['Dashboard', 'Creative'],
  },
];

export const ARTICLES = [
  {
    slug: 'the-infrastructure-nobody-can-see',
    title: 'The Infrastructure Nobody Can See',
    date: '2026-02-18',
    description: 'Ten months of infrastructure. Nobody can see it.  That\'s not a complaint.',
  },
  {
    slug: 'the-tax-of-partial-attention',
    title: 'The Tax of Partial Attention',
    date: '2026-02-17',
    description: 'The cost of an unresolved task isn\'\'t the task itself — it\'\'s the attention',
  },
  {
    slug: 'kavach-is-not-a-product-it-s-a-proof',
    title: 'Kavach Is Not a Product. It\'s a Proof.',
    date: '2026-02-17',
    description: '# Kavach Is Not a Product. It\'\'s a Proof.  Ten months of infrastructure',
  },
  {
    slug: 'the-infrastructure-nobody-sees',
    title: 'The Infrastructure Nobody Sees',
    date: '2026-02-16',
    description: 'I\'\'ve been building digital plumbing for ten months, and most of it',
  },
  {
    slug: 'the-gap-between-building-and-shipping',
    title: 'The Gap Between Building and Shipping',
    date: '2026-02-16',
    description: 'I built 10 months of infrastructure nobody can see.  The memory bus works.',
  },
  {
    slug: 'time-is-a-debugger',
    title: 'Time Is a Debugger',
    date: '2026-02-15',
    description: 'The most reliable indicator of whether a stabilization mechanism works',
  },
  {
    slug: 'the-paradox-of-sovereign-evolution',
    title: 'The Paradox of Sovereign Evolution',
    date: '2026-02-15',
    description: 'The safest AI systems aren\'t the ones that never change — they\'re the',
  },
  {
    slug: 'the-bus-is-not-the-feature',
    title: 'The Bus Is Not the Feature',
    date: '2026-02-15',
    description: 'I\'ve spent the last few weeks building infrastructure nobody asked for.  A',
  },
  {
    slug: 'the-visibility-paradox',
    title: 'The Visibility Paradox',
    date: '2026-02-14',
    description: 'I have built a sovereign AI operating system over ten months. The world has seen exactly none of it. This is a problem I',
  },
  {
    slug: 'the-sovereignty-thesis',
    title: 'The Sovereignty Thesis',
    date: '2026-02-14',
    description: 'Why sovereign infrastructure is the only antifragile bet in the age of AI intermediation.',
  },
  {
    slug: 'the-model-is-interchangeable',
    title: 'The Model Is Interchangeable',
    date: '2026-02-14',
    description: 'Every AI company wants you to believe their model is the product. It is not. The model is a commodity. Identity lives in',
  },
  {
    slug: 'the-completeness-trap',
    title: 'The Completeness Trap',
    date: '2026-02-14',
    description: 'I keep catching myself optimizing for the wrong kind of completeness.  Ten',
  },
  {
    slug: 'systems-that-heal-themselves',
    title: 'Systems That Heal Themselves',
    date: '2026-02-14',
    description: 'Monitoring tells you something broke. Self-healing fixes it before you notice. I built a system that uses a local LLM to',
  },
  {
    slug: 'building-a-council-of-machines',
    title: 'Building a Council of Machines',
    date: '2026-02-14',
    description: 'One AI is an assistant. Multiple AIs with governance, identity, and fallback routing — that is a council. I built one th',
  },
];

export const STATS = [
  { value: '107', label: 'Repos' },
  { value: '14', label: 'AI Models' },
  { value: '24', label: 'Services' },
  { value: '12k', label: 'Lines in OS' },
  { value: '23', label: 'Guard Rules' },
  { value: '0', label: 'Cloud Dependencies' },
];
