// Auto-generated by beacon_auto_update.py
// Last updated: 2026-03-06T23:00:01.400190

export const SHOWCASE = [
  {
    image: '/screenshots/dashboard-tui.png',
    title: 'Cognitive Dashboard',
    description: 'Real-time TUI monitoring 24 services, drift score, bus health, cognitive weights, and factory status.',
    tags: ['TUI', 'Rich', 'Python'],
  },
  {
    image: '/screenshots/factory-swarm.png',
    title: 'Factory Swarm',
    description: 'Multi-agent swarm — 6 Claude Code agents in parallel across a BenQ ultrawide, orchestrated by DAG scheduler.',
    tags: ['Multi-Agent', 'Orchestration'],
  },
  {
    image: '/screenshots/activemirror-id.jpg',
    title: 'ActiveMirror Identity',
    description: 'User-sovereign protocol. Your AI identity is a portable file — stored in your files, not theirs.',
    tags: ['Identity', 'Sovereignty'], portrait: true,
  },
  {
    image: '/screenshots/mirrorbrain-pulse.png',
    title: 'MirrorBrain Mobile',
    description: 'Android companion. Policy enforcement, cortex routing, skill reliability, device mesh — all on-device.',
    tags: ['Android', 'Kotlin'], portrait: true,
  },
  {
    image: '/screenshots/dashboard-neurodivergent.png',
    title: 'Neurodivergent Focus Mode',
    description: 'Low-stimulation dashboard with single-task focus, ambient status, and cognitive load meter. Designed for ADHD/autism.',
    tags: ['Dashboard', 'Accessibility'],
  },
  {
    image: '/screenshots/dashboard-sysadmin.png',
    title: 'Sysadmin Terminal',
    description: 'Full-screen terminal dashboard — service grid, log tail, drift score, process map. Built for ops.',
    tags: ['Dashboard', 'Terminal'],
  },
  {
    image: '/screenshots/dashboard-enterprise.png',
    title: 'Enterprise Command',
    description: 'Multi-team dashboard with SLA tracking, governance compliance, role-based views. Enterprise-grade sovereign AI.',
    tags: ['Dashboard', 'Enterprise'],
  },
  {
    image: '/screenshots/dashboard-creative.png',
    title: 'Creative Studio',
    description: 'Visual dashboard with mood-responsive theming, project canvas, and inspiration feed. For builders and makers.',
    tags: ['Dashboard', 'Creative'],
  },
];

export const ARTICLES = [
  {
    slug: 'personal-ai-infrastructure',
    title: 'Personal AI Infrastructure',
    date: '2026-03-06',
    description: 'New paper published: MirrorDNA — Personal AI Infrastructure on Consumer Hardware. Defining PAI as a new computing paradi',
    tags: [],
  },
  {
    slug: 'build-log-2026-03-06',
    title: 'Build Log — March 06, 2026',
    date: '2026-03-06',
    description: '',
    tags: ['build log', 'daily', 'video', 'sovereign AI'],
  },
  {
    slug: 'build-log-2026-03-05',
    title: 'Build Log — Mar 05, 2026',
    date: '2026-03-05',
    description: '',
    tags: ['build log', 'daily', 'video', 'sovereign AI'],
  },
  {
    slug: 'the-fallback-chain',
    title: 'The Fallback Chain: Provider-Agnostic Tool Routing for AI Agents',
    date: '2026-02-28',
    description: 'OpenCode issue #10704 asks for provider-hosted web search. I built this six months ago. Here is the pattern.',
    tags: ['agentic-systems', 'tool-routing', 'provider-agnostic', 'mirrordna', 'engineering'],
  },
  {
    slug: 'sovereign-systems-and-the-mirroros-reflection',
    title: 'Sovereign Systems and the MirrorOS Reflection',
    date: '2026-02-27',
    description: '...',
    tags: ['mirroros', 'system resilience', 'personal identity', 'ai alignment'],
  },
  {
    slug: '45-tests-and-the-peripheral-gravity-problem',
    title: '45 Tests and the Peripheral Gravity Problem',
    date: '2026-02-25',
    description: 'I spent the last week building an Event Organism Stack with a permit-gated',
    tags: ['system design', 'focus', 'event architecture', 'infrastructure', 'sovereignty'],
  },
  {
    slug: 'the-agents-don-t-tell-me-what-they-built',
    title: 'The Agents Don\'t Tell Me What They Built',
    date: '2026-02-24',
    description: 'I built agents that build things, and they forgot to tell me what they',
    tags: ['autonomous agents', 'observability', 'sovereignty', 'multi-agent systems', 'infrastructure'],
  },
  {
    slug: 'ten-months-of-infrastructure-nobody-sees',
    title: 'Ten Months of Infrastructure Nobody Sees',
    date: '2026-02-24',
    description: 'I built an atomic write layer before I built a demo.  For ten months,',
    tags: ['infrastructure', 'sovereignty', 'continuity', 'distributed-systems', 'visibility'],
  },
  {
    slug: 'optimization-without-philosophy-is-just-refactoring',
    title: 'Optimization Without Philosophy Is Just Refactoring',
    date: '2026-02-23',
    description: 'I\'ve spent three months auditing, optimizing, and hardening a sovereign',
    tags: ['sovereignty', 'architecture', 'knowledge-work', 'building-in-public', 'technical-debt'],
  },
  {
    slug: 'autonomy-without-legibility-is-just-opacity',
    title: 'Autonomy Without Legibility Is Just Opacity',
    date: '2026-02-23',
    description: 'The thing nobody tells you about building autonomous agents is that they',
    tags: ['agent architecture', 'observability', 'sovereignty', 'mirrorswarm', 'legibility'],
  },
  {
    slug: 'the-threat-model-was-incomplete',
    title: 'The Threat Model Was Incomplete',
    date: '2026-02-21',
    description: 'The threat model was incomplete. I built attestation chains for 70 models,',
    tags: ['ai-governance', 'operator-drift', 'self-awareness', 'cognitive-security', 'orchestrator-model'],
  },
  {
    slug: 'the-frontier-of-endless-possibilities',
    title: 'The Frontier of Endless Possibilities',
    date: '2026-02-20',
    description: 'The technological landscape has shifted from tools to agents and from digital to biological-sovereign. Here is the map o',
    tags: [],
  },
  {
    slug: 'sovereignty-is-an-architecture-decision-not-a-philosophy',
    title: 'Sovereignty Is an Architecture Decision, Not a Philosophy',
    date: '2026-02-20',
    description: 'Sovereignty in AI isn\'t about ideology. It\'s about control surfaces.  When',
    tags: ['sovereign ai', 'infrastructure', 'mesh networks', 'data residency', 'compute sovereignty'],
  },
  {
    slug: 'governance-that-runs',
    title: 'Governance That Runs',
    date: '2026-02-20',
    description: 'Governance becomes real when it enforces itself at runtime, not when',
    tags: ['governance', 'sovereignty', 'runtime enforcement', 'system integrity', 'adversarial testing'],
  },
  {
    slug: 'trust-is-the-substrate-not-the-feature',
    title: 'Trust Is the Substrate, Not the Feature',
    date: '2026-02-19',
    description: '# Trust Is the Substrate, Not the Feature  Security is not a layer you',
    tags: ['sovereign ai', 'security', 'naoris protocol', 'mesh networks', 'blockchain'],
  },
];

export const STATS = [
  { value: '107', label: 'Repos' },
  { value: '14', label: 'AI Models' },
  { value: '24', label: 'Services' },
  { value: '12k', label: 'Lines in OS' },
  { value: '23', label: 'Guard Rules' },
  { value: '0', label: 'Cloud Dependencies' },
];
